### ISSUE TITLE
Key code is different on Firefox

### ISSUE THREAD

**Issue by airtonzanon** [una/little-cli-game#3]
Morning,

I was seeing the answer file and there the code for "-" is 189, but it just works on Chrome.
When you are using Mozilla Firefox the code for "-" is 173.

So we can't play on Firefox, because the answer for "include hidden files flag" doesn't work.

Can we do something to support Firefox too? :smile:

**Comment by tomsturge** [comment]
Could detect the user agent and load a different keymap script for different browsers

**Comment by una** [comment]
Interesting! I didn't know that!

**Comment by mwrouse** [comment]
@mrmohtas I don't think adding these special cases to the code would be the most ideal solution, in my pull request I provided an alternate solution to this. 
I added an "altBinding" to the JSON, in the JS this alt binding will also be considered if it exists when verifying user input.
