### ISSUE TITLE
End game rundown

### ISSUE THREAD

**Issue by tomsturge** [una/little-cli-game#4]
Would be great to have a log of the answers (right and wrong) at the end of a round so you could learn the commands you don't know or discover the ones you got wrong

**Comment by una** [comment]
its in the console! (At least the skipped answers are)

See:

![game](https://cloud.githubusercontent.com/assets/1693164/19913378/5dcb07ba-a078-11e6-9ae1-f765bae2b38c.gif)

**Comment by tomsturge** [comment]
I'm a dumbass. It's right there in the intro text!
